openapi: 3.0.0
info:
  title: Swing Notes RESTful API
  description: API documentation using Swagger
  version: 1.0.0

tags:
  - name: Notes
    description: All endpoints related to note management.
  - name: Auth
    description: All endpoints related to user authentication and management.
paths: {}
